### ISSUE TITLE
DevConf.CZ

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/hut23-open-source-sa#24]
DevConf.CZ will be held at Faculty of Information Technology, Brno University of Technology, Czech Republic, on 13-15 June 2024. This is quite a big open source conference, so it might be interesting to submit something.

Important dates:
1. CfP opens: December 14, 2023
2. CfP closes: ~~March 3~~ March 10, 2024
3. CfP notifications: April 8-14, 2024
4. Schedule and registration: April 22-28, 2024
5. Event dates: June 13-15, 2024

More info: https://www.devconf.info/cz/

**Comment by llewelld** [comment]
As discussed during our most recent OSSA meeting, I mentioned this to @evelinag in case it was of interest; Evalina highlighted that this overlaps with HackWeek, which rather torpedoes any chance of attending.

**Comment by mhauru** [comment]
Closing this since the event has now passed.
