### ISSUE TITLE
Make hut23-open-source-sa public

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/hut23-open-source-sa#25]
As the Open Source Service Area we should be promoting the ideal of working in the open. One step towards this would be to make the project board and assocated repo public.

This would provide visibility within the Turing, make it easier for us to collaborate with people both internally and externally, and also help (in a small way) to showcase the open source work REG and the Turing is doing to the rest of the world.

The Turing Way already uses a completely open approach, and although very different to a Service Area, it's an example of the Turing doing this well.

There are a few considerations I came up with that we might need to think about.
1. Existing tickets and discussion would be made public; would this be okay?
2. Would we need to make completely clear to future contributors that it's all public?
3. Are there implications of users/email address being included on tickets?

**Comment by mhauru** [comment]
Done!
