### ISSUE TITLE
Tech talk on OSS and licences

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/hut23-open-source-sa#29]
An idea that emerged during the tech talk about FOSDEM (#27): We could have a tech talk about FOSS, its history, different licences, etc. I bet a lot of people would be interested in just understanding how copyright law and licensing works and what the differences between major licences are.

I went through the list of old tech talks to see that this hasn't been done recently, and the only relevant one I found was Eric's talk from February 2020: https://github.com/alan-turing-institute/DataScienceSkills/blob/master/software_licenses.pdf

**Comment by llewelld** [comment]
The tech talk schdules are already quite busy, so I've claimed a slot on 16 July. Plenty of time to figure out the details between now and then.

**Comment by llewelld** [comment]
@edaub's slides on the topic from the DataScienceSkill's repo that he's kindly offered for our re-use: https://github.com/alan-turing-institute/DataScienceSkills/blob/master/software_licenses.pdf

**Comment by llewelld** [comment]
PDF copy of the slides as we presented them this afternoon:

[20240716-OpenSourceLicences.pdf](https://github.com/user-attachments/files/16251919/20240716-OpenSourceLicences.pdf)

As this has now been presented, I'll close this task. Thanks @mhauru, @mastoffel; @JimMadge; really enjoyed working on this with you.
