### ISSUE TITLE
FOSDEM'25

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/hut23-open-source-sa#31]
We should think about how we want to engage with FOSDEM 2025, and whether we can get more support from REG/Turing more widely. Some thoughts include
* Can REG/Turing sponsor the event?
* Can we get the same sort of treatment for FOSDEM as we get for RSECon, where it's explicitly made known for the whole team that this is an accepted use of personal development budget, and there's going to be a group of REGers going?

This is all quite early now, so setting a calendar reminder to come back to this in August/September time.

**Comment by mhauru** [comment]
Closed in favour of #45

**Comment by llewelld** [comment]
Apologies @mhauru, I hadn't noticed this ticket when I created #45 and this one should have taken precedence. My bad.
