### ISSUE TITLE
Turing at OggCamp

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/hut23-open-source-sa#33]
Jim highlighted that OggCamp is happening again this year in Manchester, 12-13 October:

https://www.oggcamp.org/

Would there be interest from Turing people to attend?

Would it make sense to have a stand there?

**Comment by JimMadge** [comment]
I'll be going to OggCamp. Not sure if anyone else is :eyes:.

**Comment by JimMadge** [comment]
Back from OggCamp. I'll think about the best way to digest what it was like and feed that back.

**Comment by llewelld** [comment]
From your [Mastodon feed](https://fosstodon.org/@JimMadge) it looked like were having a great time; I'm looking forward to hearing about it.

**Comment by mhauru** [comment]
@JimMadge, I'll close this since it sounds like the OggCamp specific stuff is all done. Feel free to link the blogpost you mentioned and/or open another issue about the more general talk you were thinking of.

**Comment by JimMadge** [comment]
https://blog.jmadge.com/posts/oggcamp_2024/
