### ISSUE TITLE
Contribute feedback on OSI AI license draft

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/hut23-open-source-sa#37]
In the Open Source Licnces tech talk (see #29), @JimMadge highlighted that the OSI is currently [taking feedback](https://discuss.opensource.org/c/ai/5) on their draft [Open Source AI Licence definition](https://opensource.org/deepdive).

Jim also suggested that it might be worthwhile to co-ordinate a response on this.

This does feel like something the Turing should have a view on and the capacilty to contribute to.

So, this task is to figure out the details: is this already being done within the Turing? Is this something that should be done? Who should do it? Would the OSSA like to be involved somehow?

**Comment by mhauru** [comment]
Feedback seems to currently be gathered as comments to a HackMD, see latest draft version here: https://opensource.org/deepdive/drafts

**Comment by JimMadge** [comment]
Tagging some people from TPS who might be interested and contributed to the coffee chat about this, @Arielle-Bennett, @dingaaling, @gedankenstuecke, @davsarper.

**Comment by JimMadge** [comment]
Putting my notes from a conversation with @dingaaling before I forget (they might not make sense until there is more context 😅)

- What is the difference between providing information to retrieve data and making the data open?
  - It might be worth adding some detail on the decision here to head off criticism
  - Is this approach limited by current technology? Should we say something about what might be possible in the future? Open Source AI + Data
- Breaking down AI systems into components which use the most appropriate licenses is great
  - Good to acknowledge that AI systems are not just code, and build on the work of other open communities (_e.g._ Creative Commons)

**Comment by llewelld** [comment]
We discussed this during the OSSA meeting on 2024-07-31. We concluded:
1. Lots of enthusiasm but it really needs someone to champion it.
2. Institutional support would be useful to allow people to put in the time.

Due to other commitments we didn't have any volunteers to help lobby for institutional support, and given this is likely to be quite a high-commitment activity, it was decided not to pursue it.

I'm therefore closing the issue. If the situation changes, please feel free to re-open it.

**Comment by llewelld** [comment]
As highlighted ni the recent TPS newsletter. I know we don't have active plans to contribute, but hopefully it's still of interest...

https://opensource.org/blog/community-input-drives-the-new-draft-of-the-open-source-ai-definition#msdynmkt_trackingcontext=87c42f3b-3b8c-4ecd-8c32-772d63a98e99
