### ISSUE TITLE
Arrange talk on OSPOs in relation to the Turing

### ISSUE THREAD

**Issue by llewelld** [alan-turing-institute/hut23-open-source-sa#39]
An OSPO is an [Open Source Program Office](https://www.redhat.com/en/blog/what-does-open-source-program-office-do). These are becoming increasingly popular within organisations to help unify the approach to open source within the organisation (both usage of and contribution to).

@malvikasharan and @Arielle-Bennett recently attended the [OSPOs for Good 2024](https://www.un.org/techenvoy/content/ospos-good-2024) symposium at the UN in New York. 

In a recent discussion following the OSS Tech Talk (see #29) the topic was discussed and @malvikasharan highlighted how at the Turing, Core Capability such as RCM+REG+RAM could potentially play the role of OSPO and that she's planning to do some work on this over the coming months.

It would be great to have @malvikasharan, @Arielle-Bennett and others with ideas on the topic to give a Tech Talk about OSPOs and how REG capability relates to it.

This could be practically beneficial to REG members, for example wanting to know who to talk to about Turing policies around open source, where to get Turing-specific licensing advice, where to get help within the Turing on open source community building, and so on.

**Comment by Arielle-Bennett** [comment]
Hey @malvikasharan would next Tuesday (30th) work for you? Otherwise 3rd of September would work for me 😄

**Comment by llewelld** [comment]
@Arielle-Bennett, @malvikasharan: we discussed this at the meeting today and we'd still be really interested to have a tech talk on the topic. The next available slots are now 15 or 22 October but beyond those dates would also work.  Would you still be up for this?

**Comment by llewelld** [comment]
For those attending RSECon'24 next week, there will be a talk on OSPOs on Wednesday that may also be of interest:

["What is an OSPO and how are we creating one at UCL?"](https://virtual.oxfordabstracts.com/#/event/49081/submission/7), David Pérez-Suárez¹, Mosè Giordano¹, Jonathan Cooper¹, David Stansby¹, Stephen Thompson¹, Miguel Xochicale¹, Adam Tyson².

<sup>
1. UCL / ARC, United Kingdom; 2. he Sainsbury Wellcome Centre, United Kingdom.
</sup>

**Comment by Arielle-Bennett** [comment]
Hi @llewelld can you please pencil me in for 15 October? I'll be in the office, hopefully Malvika can join us as well

**Comment by malvikasharan** [comment]
15 Oct works better for me too.
We can invite David to join us - I have been contributing to the UCL OSPO and collaborating with David. He can share his journey so far trying to move from RSE role to dedicated OSPO.

**Comment by llewelld** [comment]
It was a great talk and with lots of engagement; thank you @Arielle-Bennett and @malvikasharan.

Would you be willing to share your slides (publicly) by linking them from this ticket?

**Comment by JimMadge** [comment]
I missed it 😱!

**Comment by Arielle-Bennett** [comment]
Slides are here: https://docs.google.com/presentation/d/1ET0ZrSiJzYNZeuS1z-geoPBu6XPt5o8Kp2erVOz6SWE/edit?usp=sharing with credit to @malvikasharan for putting them together this morning ❤️ 

@JimMadge we did also record portions of the presentation so you should be able to watch it back :)

**Comment by LevanBokeria** [comment]
[Recording now up!](https://thealanturininstitute.sharepoint.com/:f:/s/ResearchEngineering/EjvGgN5xc5dEhDHDxjuhagYB_sAK0-nAzApJ8KUxCz4tJg?e=KntRmw)

**Comment by llewelld** [comment]
I think it's safe to close this now (please re-open if I misunderstood). It would be interesting to think about how to progress this further at the Turing.
